// https://www.data.gouv.fr/fr/datasets/etats-et-capitales-du-monde/
export default [		
    {nom:"d’Abou Dabi", booleen:true},
    {nom:"d’Abuja", booleen:true},
    {nom:"d’Accra", booleen:true},
    {nom:"d’Achgabat", booleen:true},
    {nom:"d’Addis Abeba", booleen:true},
    {nom:"d’Alger", booleen:true},
    {nom:"d’Alofi", booleen:true},
    {nom:"d’Amman", booleen:true},
    {nom:"d’Amsterdam", booleen:true},
    {nom:"d’Andorre-la-Vieille", booleen:true},
    {nom:"d’Ankara", booleen:true},
    {nom:"d’Antananarivo", booleen:true},
    {nom:"d’Apia", booleen:true},
    {nom:"d’Asmara", booleen:true},
    {nom:"d’Asuncion", booleen:true},
    {nom:"d’Athènes", booleen:true},
    {nom:"d’Avarua", booleen:true},
    {nom:"de Bagdad", booleen:true},
    {nom:"de Bairiki", booleen:true},
    {nom:"de Bakou", booleen:true},
    {nom:"de Bamako", booleen:true},
    {nom:"de Bandar Seri Begawan", booleen:true},
    {nom:"de Bangkok", booleen:true},
    {nom:"de Bangui", booleen:true},
    {nom:"de Banjul", booleen:true},
    {nom:"de Basseterre", booleen:true},
    {nom:"de Belgrade", booleen:true},
    {nom:"de Belmopan", booleen:true},
    {nom:"de Berlin", booleen:true},
    {nom:"de Berne", booleen:true},
    {nom:"de Beyrouth", booleen:true},
    {nom:"de Bichkek", booleen:true},
    {nom:"de Bissao", booleen:true},
    {nom:"de Bogota", booleen:true},
    {nom:"de Brasilia", booleen:true},
    {nom:"de Bratislava", booleen:true},
    {nom:"de Brazzaville", booleen:true},
    {nom:"de Bridgetown", booleen:true},
    {nom:"de Bruxelles", booleen:true},
    {nom:"de Bucarest", booleen:true},
    {nom:"de Budapest", booleen:true},
    {nom:"de Buenos Aires", booleen:true},
    {nom:"de Canberra", booleen:true},
    {nom:"de Caracas", booleen:true},
    {nom:"de Castries", booleen:true},
    {nom:"de Chisinau", booleen:true},
    {nom:"de Conakry", booleen:true},
    {nom:"de Copenhague", booleen:true},
    {nom:"de Dacca", booleen:true},
    {nom:"de Dakar", booleen:true},
    {nom:"de Damas", booleen:true},
    {nom:"de Delap-Uliga-Darrit", booleen:true},
    {nom:"de Dili", booleen:true},
    {nom:"de Djibouti", booleen:true},
    {nom:"de Djouba", booleen:true},
    {nom:"de Dodoma", booleen:true},
    {nom:"de Doha", booleen:true},
    {nom:"de Douchanbé", booleen:true},
    {nom:"de Dublin", booleen:true},
    {nom:"d’Erevan", booleen:true},
    {nom:"de Freetown", booleen:true},
    {nom:"de Gaborone", booleen:true},
    {nom:"de Georgetown", booleen:true},
    {nom:"de Gitega", booleen:true},
    {nom:"de Guatémala City", booleen:true},
    {nom:"de Hanoï", booleen:true},
    {nom:"d’Hararé", booleen:true},
    {nom:"d’Helsinki", booleen:true},
    {nom:"de Honiara", booleen:true},
    {nom:"d’Islamabad", booleen:true},
    {nom:"de Jakarta", booleen:true},
    {nom:"de Kaboul", booleen:true},
    {nom:"de Kampala", booleen:true},
    {nom:"de Katmandou", booleen:true},
    {nom:"de Khartoum", booleen:true},
    {nom:"de Kiev", booleen:true},
    {nom:"de Kigali", booleen:true},
    {nom:"de Kingston", booleen:true},
    {nom:"de Kingstown", booleen:true},
    {nom:"de Kinshasa", booleen:true},
    {nom:"de Koweït", booleen:true},
    {nom:"de Kuala Lumpur", booleen:true},
    {nom:"de La Havane", booleen:true},
    {nom:"de La Valette", booleen:true},
    {nom:"du Caire", booleen:true},
    {nom:"de Libreville", booleen:true},
    {nom:"de Lilongwé", booleen:true},
    {nom:"de Lima", booleen:true},
    {nom:"de Lisbonne", booleen:true},
    {nom:"de Ljubljana", booleen:true},
    {nom:"de Lomé", booleen:true},
    {nom:"de Londres", booleen:true},
    {nom:"de Luanda", booleen:true},
    {nom:"de Lusaka", booleen:true},
    {nom:"de Luxembourg", booleen:true},
    {nom:"de Madrid", booleen:true},
    {nom:"de Malabo", booleen:true},
    {nom:"de Malé", booleen:true},
    {nom:"de Managua", booleen:true},
    {nom:"de Manama", booleen:true},
    {nom:"de Manille", booleen:true},
    {nom:"de Maputo", booleen:true},
    {nom:"de Mascate", booleen:true},
    {nom:"de Maséru", booleen:true},
    {nom:"de Mbabané", booleen:true},
    {nom:"de Melekeok", booleen:true},
    {nom:"de Mexico", booleen:true},
    {nom:"de Minsk", booleen:true},
    {nom:"de Mogadiscio", booleen:true},
    {nom:"de Monaco", booleen:true},
    {nom:"de Monrovia", booleen:true},
    {nom:"de Montévidéo", booleen:true},
    {nom:"de Moroni", booleen:true},
    {nom:"de Moscou", booleen:true},
    {nom:"de Nairobi", booleen:true},
    {nom:"de Nassau", booleen:true},
    {nom:"de Naypyidaw", booleen:true},
    {nom:"de Ndjamena", booleen:true},
    {nom:"de New Delhi", booleen:true},
    {nom:"de Niamey", booleen:true},
    {nom:"de Nicosie", booleen:true},
    {nom:"de Nouakchott", booleen:true},
    {nom:"de Nour-Soultan", booleen:true},
    {nom:"de Nuku’alofa", booleen:true},
    {nom:"de Oslo", booleen:true},
    {nom:"d’Ottawa", booleen:true},
    {nom:"de Ouagadougou", booleen:true},
    {nom:"d’Oulan-Bator", booleen:true},
    {nom:"de Palikir", booleen:true},
    {nom:"de Panama", booleen:true},
    {nom:"de Paramaribo", booleen:true},
    {nom:"de Phnom Penh", booleen:true},
    {nom:"de Podgorica", booleen:true},
    {nom:"de Port Moresby", booleen:true},
    {nom:"de Port-Louis", booleen:true},
    {nom:"de Port-Vila", booleen:true},
    {nom:"de Port-au-Prince", booleen:true},
    {nom:"de Port-d’Espagne", booleen:true},
    {nom:"de Porto-Novo", booleen:true},
    {nom:"de Prague", booleen:true},
    {nom:"de Praia", booleen:true},
    {nom:"de Pristina", booleen:true},
    {nom:"de Prétoria", booleen:true},
    {nom:"de Pyongyang", booleen:true},
    {nom:"de Pékin", booleen:true},
    {nom:"de Quito", booleen:true},
    {nom:"de Rabat", booleen:true},
    {nom:"de Reykjavik", booleen:true},
    {nom:"de Riga", booleen:true},
    {nom:"de Riyad", booleen:true},
    {nom:"de Rome", booleen:true},
    {nom:"de Roseau", booleen:true},
    {nom:"de Saint John’s", booleen:true},
    {nom:"de Saint-Domingue", booleen:true},
    {nom:"de Saint-Georges", booleen:true},
    {nom:"de Saint-Marin", booleen:true},
    {nom:"de San José", booleen:true},
    {nom:"de San Salvador", booleen:true},
    {nom:"de Sanaa", booleen:true},
    {nom:"de Santiago", booleen:true},
    {nom:"de Sao Tomé", booleen:true},
    {nom:"de Sarajevo", booleen:true},
    {nom:"de Singapour", booleen:true},
    {nom:"de Skopje", booleen:true},
    {nom:"de Sofia", booleen:true},
    //{nom:"de Sri Jayewardenepura-Kotte", booleen:true}, Sri Lanka, trop long
    {nom:"de Stockholm", booleen:true},
    {nom:"de La Paz", booleen:true},
    {nom:"de Suva", booleen:true},
    {nom:"de Séoul", booleen:true},
    {nom:"de Tachkent", booleen:true},
    {nom:"de Tallinn", booleen:true},
    {nom:"de Tbilissi", booleen:true},
    {nom:"de Thimphou", booleen:true},
    {nom:"de Tirana", booleen:true},
    {nom:"de Tokyo", booleen:true},
    {nom:"de Tripoli", booleen:true},
    {nom:"de Tunis", booleen:true},
    {nom:"de Tégucigalpa", booleen:true},
    {nom:"de Téhéran", booleen:true},
    {nom:"de Vaduz", booleen:true},
    {nom:"de Vaiaku", booleen:true},
    {nom:"de Varsovie", booleen:true},
    {nom:"de Victoria", booleen:true},
    {nom:"de Vienne", booleen:true},
    {nom:"de Vientiane", booleen:true},
    {nom:"de Vilnius", booleen:true},
    {nom:"de Washington", booleen:true},
    {nom:"de Wellington", booleen:true},
    {nom:"de Windhoek", booleen:true},
    {nom:"de Yamoussoukro", booleen:true},
    {nom:"de Yaoundé", booleen:true},
    {nom:"de Yaren", booleen:true},
    {nom:"de Zagreb", booleen:true}
];
