//https://fr.wikipedia.org/wiki/Liste_des_fleuves_de_France
const fleuvesMetro = [
    {nom:"de l’Aa", booleen: true},
    {nom:"de l’Abatesco", booleen: true},
    {nom:"de l’Aber-Benoît", booleen: true},
    {nom:"de l’Aber-Ildut", booleen: true},
    {nom:"de l’Aber-Wrac’h", booleen: true},
    {nom:"de l’Acqua Tignese", booleen: true},
    {nom:"de l’Adour", booleen: true},
    {nom:"de l’Agay", booleen: true},
    {nom:"de l’Agly", booleen: true},
    {nom:"de l’Alesani", booleen: true},
    {nom:"de l’Aliso", booleen: true},
    {nom:"de l’Alistro", booleen: true},
    {nom:"de l’Arc", booleen: true},
    {nom:"de l’Argens", booleen: true},
    {nom:"du Riou de l’Argentière", booleen: true},
    {nom:"de l’Arguenon", booleen: true},
    {nom:"de l’Arques", booleen: true},
    {nom:"de l’Aude", booleen: true},
    {nom:"de l’Aulne", booleen: true},
    {nom:"de l’Authie", booleen: true},
    {nom:"de l’Auzance", booleen: true},
    {nom:"de l’Aven", booleen: true},
    {nom:"de l’Ay", booleen: true},
    {nom:"de la Baillaury", booleen: true},
    {nom:"du Baraci", booleen: true},
    {nom:"du Batailler", booleen: true},
    {nom:"du Bélon", booleen: true},
    {nom:"du Bevinco", booleen: true},
    {nom:"de la Bidassoa", booleen: true},
    {nom:"du Blavet", booleen: true},
    {nom:"du Boivre", booleen: true},
    {nom:"du Borrigo", booleen: true},
    {nom:"du Boscq", booleen: true},
    {nom:"du Boudigau", booleen: true},
    {nom:"de la Brague", booleen: true},
    {nom:"de la Bravona", booleen: true},
    {nom:"de la Bresle", booleen: true},
    {nom:"du Buccatoggio", booleen: true},
    {nom:"du Buggiu", booleen: true},
    {nom:"du Butturacci", booleen: true},
    {nom:"de la Cagne", booleen: true},
    {nom:"de la Canche", booleen: true},
    {nom:"du Canella", booleen: true},
    {nom:"du Careï", booleen: true},
    {nom:"du Cavo", booleen: true},
    {nom:"de la Charente", booleen: true},
    {nom:"du Chiola", booleen: true},
    {nom:"du Chiosura", booleen: true},
    {nom:"du Chiuni", booleen: true},
    {nom:"du Couesnon", booleen: true},
    {nom:"du Courant d’Huchet", booleen: true},
    {nom:"du Courant de Contis", booleen: true},
    {nom:"du Courant de Mimizan", booleen: true},
    {nom:"du Courant de Soustons", booleen: true},
    {nom:"du Curé", booleen: true},
    {nom:"du Dardo", booleen: true},
    {nom:"de la Dives", booleen: true},
    {nom:"de la Divette", booleen: true},
    {nom:"de la Dordogne", booleen: true},
    {nom:"du Dourduff", booleen: true},
    {nom:"du Douron", booleen: true},
    {nom:"de la Douve", booleen: true},
    {nom:"du Drochon", booleen: true},
    {nom:"du Dun", booleen: true},
    {nom:"de la Durdent", booleen: true},
    {nom:"de l’Ellé", booleen: true},
    {nom:"de l’Élorn", booleen: true},
    {nom:"de l’Escaut", booleen: true},
    {nom:"de la Rivière d’Étel", booleen: true},
    {nom:"de l’Eygoutier", booleen: true},
    {nom:"du Falleron", booleen: true},
    {nom:"du Fango", booleen: true},
    {nom:"de la Figarella", booleen: true},
    {nom:"du Fium’Albino", booleen: true},
    {nom:"du Fium’Alto", booleen: true},
    {nom:"du Fiume Santu", booleen: true},
    {nom:"du Fiumorbo", booleen: true},
    {nom:"de la Flèche", booleen: true},
    {nom:"de la Flora", booleen: true},
    {nom:"du Fossan", booleen: true},
    {nom:"du Francolu", booleen: true},
    {nom:"du Frémur", booleen: true},
    {nom:"du Gapeau", booleen: true},
    {nom:"de la Garonne", booleen: true},
    {nom:"de la Gironde", booleen: true},
    {nom:"de l’Estuaire de la Gironde", booleen: true},
    {nom:"de la Giscle", booleen: true},
    {nom:"du Golo", booleen: true},
    {nom:"du Gorbio", booleen: true},
    {nom:"du Gouessant", booleen: true},
    {nom:"du Gouët", booleen: true},
    {nom:"du Goyen", booleen: true},
    {nom:"du Grand Vallat", booleen: true},
    {nom:"de la Grande Frayère", booleen: true},
    {nom:"du Guillec", booleen: true},
    {nom:"du Guyoult", booleen: true},
    {nom:"de l’Hérault", booleen: true},
    {nom:"de l’Horn", booleen: true},
    {nom:"de l’Huveaune", booleen: true},
    {nom:"de l’Ic", booleen: true},
    {nom:"de l’Isole", booleen: true},
    {nom:"du Jaudy", booleen: true},
    {nom:"du Kerdu", booleen: true},
    {nom:"du Lagunienu", booleen: true},
    {nom:"de la Laïta", booleen: true},
    {nom:"du Las", booleen: true},
    {nom:"du Lava", booleen: true},
    {nom:"du Lay", booleen: true},
    {nom:"du Léguer", booleen: true},
    {nom:"de la Lerre", booleen: true},
    {nom:"du Lez", booleen: true},
    {nom:"du Liamone", booleen: true},
    {nom:"de la Liane", booleen: true},
    {nom:"du Libron", booleen: true},
    {nom:"du Liscia", booleen: true},
    {nom:"du Liscu", booleen: true},
    {nom:"de la Loire", booleen: true},
    {nom:"du Loup", booleen: true},
    {nom:"du Luri", booleen: true},
    {nom:"du Magnan", booleen: true},
    {nom:"du Maravenne", booleen: true},
    {nom:"de la Marle", booleen: true},
    {nom:"de la Massane", booleen: true},
    {nom:"de la Maye", booleen: true},
    {nom:"de la Meuse", booleen: true},
    {nom:"du Minaouët", booleen: true},
    {nom:"de la Rivière de Morlaix", booleen: true},
    {nom:"du Moros", booleen: true},
    {nom:"de la Nivelle", booleen: true},
    {nom:"de la Rivière de Noyalo", booleen: true},
    {nom:"de l’Odet", booleen: true},
    {nom:"de la Rivière d’Olmeta", booleen: true},
    {nom:"de l’Orb", booleen: true},
    {nom:"de l’Orne", booleen: true},
    {nom:"de l’Ortolo", booleen: true},
    {nom:"de l’Oso", booleen: true},
    {nom:"de l’Ostriconi", booleen: true},
    {nom:"du Paillon", booleen: true},
    {nom:"du Pellegrin", booleen: true},
    {nom:"de la Rivière de Penerf", booleen: true},
    {nom:"du Penfeld", booleen: true},
    {nom:"du Penzé", booleen: true},
    {nom:"du ruisseau de Pietracorbara", booleen: true},
    {nom:"du Poggiolo", booleen: true},
    {nom:"de la Rivière de Pont-l’Abbé", booleen: true},
    {nom:"du Porto", booleen: true},
    {nom:"du Préconil", booleen: true},
    {nom:"du Prunelli", booleen: true},
    {nom:"du Quillimadec", booleen: true},
    {nom:"de la Rance", booleen: true},
    {nom:"du Ravaner", booleen: true},
    {nom:"du Fiume di Regino", booleen: true},
    {nom:"de la Reppe", booleen: true},
    {nom:"du Rhin", booleen: true},
    {nom:"du Rhône", booleen: true},
    {nom:"de la Riberette", booleen: true},
    {nom:"du Rizzanese", booleen: true},
    {nom:"du Roscoat", booleen: true},
    {nom:"du Roubaud", booleen: true},
    {nom:"de la Roya", booleen: true},
    {nom:"de la Saâne", booleen: true},
    {nom:"du Sagone", booleen: true},
    {nom:"de la Saigue", booleen: true},
    {nom:"de la Rivière Saint-Éloi", booleen: true},
    {nom:"de la Saire", booleen: true},
    {nom:"de la Scie", booleen: true},
    {nom:"du Scorff", booleen: true},
    {nom:"du Fiume Seccu", booleen: true},
    {nom:"de la Sée", booleen: true},
    {nom:"de la Seine", booleen: true},
    {nom:"de la Sélune", booleen: true},
    {nom:"de la Seudre", booleen: true},
    {nom:"de la Seulles", booleen: true},
    {nom:"de la Sèvre Niortaise", booleen: true},
    {nom:"de la Siagne", booleen: true},
    {nom:"de la Sienne", booleen: true},
    {nom:"de la Sinope", booleen: true},
    {nom:"du ruisseau de Sisco", booleen: true},
    {nom:"de la Slack", booleen: true},
    {nom:"de la Solenzara", booleen: true},
    {nom:"de la Somme", booleen: true},
    {nom:"du Stabiacciu", booleen: true},
    {nom:"du Taravo", booleen: true},
    {nom:"du Tavignano", booleen: true},
    {nom:"du Tech", booleen: true},
    {nom:"du Ter", booleen: true},
    {nom:"de la Têt", booleen: true},
    {nom:"du Thar", booleen: true},
    {nom:"de la Touloubre", booleen: true},
    {nom:"de la Touques", booleen: true},
    {nom:"du Travo", booleen: true},
    {nom:"du Trieux", booleen: true},
    {nom:"de l’U Guadu Grande", booleen: true},
    {nom:"de l’Uhabia", booleen: true},
    {nom:"de l’Untxin", booleen: true},
    {nom:"de la Valmont", booleen: true},
    {nom:"de la Vanlée", booleen: true},
    {nom:"du Var", booleen: true},
    {nom:"de la Ventilegne", booleen: true},
    {nom:"de la Veules", booleen: true},
    {nom:"du Vidourle", booleen: true},
    {nom:"de la Vie", booleen: true},
    {nom:"de la Vilaine", booleen: true},
    {nom:"du Vincin", booleen: true},
    {nom:"de la Vire", booleen: true},
    {nom:"du Vistre", booleen: true},
    {nom:"de la Warrenne", booleen: true},
    {nom:"du Yar", booleen: true},
    {nom:"de l’Yères", booleen: true},
    {nom:"de l’Yser", booleen: true}
];


//Réunion
const reunion = [
    {nom:"de la Rivière d’Abord", booleen: true},
    {nom:"de la Rivière de l’Est", booleen: true},
    {nom:"de la Rivière des Galets", booleen: true},
    {nom:"de la Rivière Langevin", booleen: true},
    {nom:"de la Rivière des Marsouins", booleen: true},
    {nom:"de la Rivière du Mât", booleen: true},
    {nom:"de la Rivière des Pluies", booleen: true},
    {nom:"de la Rivière des Remparts", booleen: true},
    {nom:"de la Rivière des Roches", booleen: true},
    {nom:"de la Rivière Saint-Denis", booleen: true},
    {nom:"de la Rivière Saint-Étienne", booleen: true},
    {nom:"de la Ravine Saint-Gilles", booleen: true},
    {nom:"de la Rivière Saint-Jean", booleen: true},
    {nom:"de la Rivière Sainte-Suzanne", booleen: true},
];

const guadeloupe = [
    {nom:"de la Grande Rivière à Goyaves", booleen: true},
    {nom:"de la Lézarde", booleen: true},
    {nom:"de la Grande Rivière des Vieux-Habitants", booleen: true},
    {nom:"de la Rivière Moustique ", booleen: true},
    {nom:"de la Grande Rivière de la Capesterre", booleen: true},
    {nom:"de la Rivière la Rose", booleen: true},
    {nom:"de la Petite Rivière à Goyave", booleen: true},
    {nom:"de la Rivière du Grand Carbet", booleen: true},
    {nom:"de la Rivière du Pérou", booleen: true},
    {nom:"de la Galion", booleen: true},
    {nom:"de la Rivière de Sainte-Marie", booleen: true},
    {nom:"de la Rivière des Pères", booleen: true},
    {nom:"de la Rivière de Beaugendre", booleen: true},
    {nom:"de la Rivière du Petit Carbet", booleen: true},
    {nom:"de la Rivière Grande Anse", booleen: true},
    {nom:"de la Rivière du Plessis", booleen: true},
    {nom:"de la Rivière du Lamentin", booleen: true},
    {nom:"de la Rivière la Sarcelle", booleen: true},
    {nom:"de la Rivière Lostau", booleen: true},
    {nom:"de la Rivière Grande Plaine", booleen: true},
    {nom:"de la Rivière du Baillif", booleen: true},
    {nom:"de la Rivière Petite Plaine", booleen: true},
    {nom:"de la Rivière du Bananier", booleen: true},
    {nom:"de la Rivière Bourceau", booleen: true},
    {nom:"de la Rivière de Baille-Argent", booleen: true},
    {nom:"de la Rivière aux Herbes", booleen: true}
];

const guyane = [
    {nom:"du Maroni", booleen:true},
    {nom:"de l’Oyapock", booleen:true},
    {nom:"de la Mana", booleen:true},
    {nom:"de l’Approuague", booleen:true},
    {nom:"du Sinnamary", booleen:true},
    {nom:"du Mahury", booleen:true},
    {nom:"de l’Iracoubo", booleen:true},
    {nom:"du Kourou", booleen:true},
    {nom:"de l’Organabo", booleen:true},
];

const estuaires = [
    {nom:"de l’Estuaire de la Loire", booleen: true},
    {nom:"de la baie du Mont-Saint-Michel", booleen:true},
    {nom:"de la baie de l’Aiguillon", booleen:true},
    {nom:"de la baie de Somme", booleen:true},
    {nom:"de la baie des Veys", booleen:true},
    {nom:"de la baie de Txingudi", booleen: true}
];

const liste =  [...fleuvesMetro, ...guadeloupe, ...guyane, ...reunion, ...estuaires];
export default liste;
